### ISSUE TITLE
Multi-level categories, but not Legacy?

### ISSUE THREAD

**Issue by perrycbrown** [belltown/Roku-NewVideoPlayer#3]
Very grateful for your examples of Roku app with multi-level categories -- just what I was looking for!

But do you have -- or know of -- a similar multi-level example that does not use deprecated, Legacy functions?

Thanks!

**Comment by belltown** [comment]
I'm not aware of a channel implemented using Scene Graph that provides multi-level categories in the same manner as NewVideoPlayer. The closest I could find is: [https://github.com/rokudev/videoplayer-channel](https://github.com/rokudev/videoplayer-channel), which is the Scene Graph version of the original VideoPlayer Channel upon which NewVideoPlayer was based.
