### ISSUE TITLE
PLEASE MAKE UPDATED VERSION OF THIS

### ISSUE THREAD

**Issue by HumongousWin** [belltown/Roku-NewVideoPlayer#4]
Just wanted to ask if you could create an updated, optimized version of Roku-NewVideoPlayer for so many of us please. If you could make a version for videoAd- and subscription-based Roku channels it would be greatly appreciated by many people.
I guess this isn't really an "issue" but a request.

**Comment by belltown** [comment]
I'm no longer doing any Roku development. In any case, to develop what you're asking for would require a complete re-write of the code, since it uses the legacy SDK, which has been deprecated.
